[2024-11-05T14:46:43.343+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T14:46:43.376+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T14:46:11.363386+00:00 [queued]>
[2024-11-05T14:46:43.397+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T14:46:11.363386+00:00 [queued]>
[2024-11-05T14:46:43.398+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-05T14:46:43.443+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): test_api> on 2024-11-05 14:46:11.363386+00:00
[2024-11-05T14:46:43.468+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_test_v1', 'test_api', 'manual__2024-11-05T14:46:11.363386+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/Weather_etl_dag.py', '--cfg-path', '/tmp/tmp22qjtjex']
[2024-11-05T14:46:43.471+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask test_api
[2024-11-05T14:46:43.474+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1451) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-05T14:46:43.475+0000] {standard_task_runner.py:72} INFO - Started process 1452 to run task
[2024-11-05T14:46:43.535+0000] {task_command.py:467} INFO - Running <TaskInstance: api_test_v1.test_api manual__2024-11-05T14:46:11.363386+00:00 [running]> on host f0df3d9af11e
[2024-11-05T14:46:44.241+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='api_test_v1' AIRFLOW_CTX_TASK_ID='test_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T14:46:11.363386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T14:46:11.363386+00:00'
[2024-11-05T14:46:44.244+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T14:46:44.300+0000] {logging_mixin.py:190} INFO - https://api.openweathermap.org/data/2.5/weather?lat=6.175108444784084&lon=49.111459997943115&appid=54ce3be99b6d93efb221eee5b5a8b52a
[2024-11-05T14:46:44.891+0000] {logging_mixin.py:190} INFO - Could not create Spark Session due to [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-11-05T14:46:44.892+0000] {logging_mixin.py:190} INFO - Exception when get request : cannot access local variable 'spark_s' where it is not associated with a value
[2024-11-05T14:46:44.893+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-05T14:46:44.924+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T14:46:44.925+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=api_test_v1, task_id=test_api, run_id=manual__2024-11-05T14:46:11.363386+00:00, execution_date=20241105T144611, start_date=20241105T144643, end_date=20241105T144644
[2024-11-05T14:46:44.983+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T14:46:45.002+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T14:46:45.005+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
