[2024-11-08T09:30:27.066+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-08T09:30:27.083+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-08T09:30:25.523534+00:00 [queued]>
[2024-11-08T09:30:27.091+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-08T09:30:25.523534+00:00 [queued]>
[2024-11-08T09:30:27.092+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-08T09:30:27.108+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): test_api> on 2024-11-08 09:30:25.523534+00:00
[2024-11-08T09:30:27.117+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_test_v1', 'test_api', 'manual__2024-11-08T09:30:25.523534+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/Weather_etl_dag.py', '--cfg-path', '/tmp/tmpgnnsk8jy']
[2024-11-08T09:30:27.120+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=360) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-08T09:30:27.121+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask test_api
[2024-11-08T09:30:27.122+0000] {standard_task_runner.py:72} INFO - Started process 362 to run task
[2024-11-08T09:30:27.235+0000] {task_command.py:467} INFO - Running <TaskInstance: api_test_v1.test_api manual__2024-11-08T09:30:25.523534+00:00 [running]> on host 61d6b7a8a242
[2024-11-08T09:30:27.346+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='api_test_v1' AIRFLOW_CTX_TASK_ID='test_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T09:30:25.523534+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-08T09:30:25.523534+00:00'
[2024-11-08T09:30:27.348+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-08T09:30:29.542+0000] {logging_mixin.py:190} INFO - Could not create Spark Session due to [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-11-08T09:30:29.543+0000] {logging_mixin.py:190} INFO - Exception when get request : cannot access local variable 'spark_s' where it is not associated with a value
[2024-11-08T09:30:29.544+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-08T09:30:29.569+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-08T09:30:29.571+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=api_test_v1, task_id=test_api, run_id=manual__2024-11-08T09:30:25.523534+00:00, execution_date=20241108T093025, start_date=20241108T093027, end_date=20241108T093029
[2024-11-08T09:30:29.631+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-08T09:30:29.651+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-08T09:30:29.654+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
