[2024-11-05T15:18:10.594+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T15:18:10.613+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T14:46:11.363386+00:00 [queued]>
[2024-11-05T15:18:10.621+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T14:46:11.363386+00:00 [queued]>
[2024-11-05T15:18:10.622+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 8
[2024-11-05T15:18:10.635+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): test_api> on 2024-11-05 14:46:11.363386+00:00
[2024-11-05T15:18:10.643+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_test_v1', 'test_api', 'manual__2024-11-05T14:46:11.363386+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/Weather_etl_dag.py', '--cfg-path', '/tmp/tmp0vd5cvi9']
[2024-11-05T15:18:10.647+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask test_api
[2024-11-05T15:18:10.648+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=192) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-05T15:18:10.649+0000] {standard_task_runner.py:72} INFO - Started process 193 to run task
[2024-11-05T15:18:10.700+0000] {task_command.py:467} INFO - Running <TaskInstance: api_test_v1.test_api manual__2024-11-05T14:46:11.363386+00:00 [running]> on host c63590717d3f
[2024-11-05T15:18:10.788+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='api_test_v1' AIRFLOW_CTX_TASK_ID='test_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T14:46:11.363386+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T14:46:11.363386+00:00'
[2024-11-05T15:18:10.790+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T15:18:11.746+0000] {logging_mixin.py:190} INFO - Could not create Spark Session due to [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-11-05T15:18:11.750+0000] {logging_mixin.py:190} INFO - Exception when get request : cannot access local variable 'spark_s' where it is not associated with a value
[2024-11-05T15:18:11.753+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-05T15:18:11.774+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T15:18:11.776+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=api_test_v1, task_id=test_api, run_id=manual__2024-11-05T14:46:11.363386+00:00, execution_date=20241105T144611, start_date=20241105T151810, end_date=20241105T151811
[2024-11-05T15:18:11.834+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T15:18:11.861+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T15:18:11.866+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
