[2024-11-08T09:30:27.068+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-08T09:30:27.085+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_test_v1.test_api scheduled__2024-11-07T00:00:00+00:00 [queued]>
[2024-11-08T09:30:27.093+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_test_v1.test_api scheduled__2024-11-07T00:00:00+00:00 [queued]>
[2024-11-08T09:30:27.094+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-08T09:30:27.111+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): test_api> on 2024-11-07 00:00:00+00:00
[2024-11-08T09:30:27.120+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_test_v1', 'test_api', 'scheduled__2024-11-07T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/Weather_etl_dag.py', '--cfg-path', '/tmp/tmpbirjuv85']
[2024-11-08T09:30:27.123+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask test_api
[2024-11-08T09:30:27.123+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=361) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-08T09:30:27.125+0000] {standard_task_runner.py:72} INFO - Started process 363 to run task
[2024-11-08T09:30:27.242+0000] {task_command.py:467} INFO - Running <TaskInstance: api_test_v1.test_api scheduled__2024-11-07T00:00:00+00:00 [running]> on host 61d6b7a8a242
[2024-11-08T09:30:28.676+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='api_test_v1' AIRFLOW_CTX_TASK_ID='test_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-07T00:00:00+00:00'
[2024-11-08T09:30:28.678+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-08T09:30:29.494+0000] {logging_mixin.py:190} INFO - Could not create Spark Session due to [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-11-08T09:30:29.495+0000] {logging_mixin.py:190} INFO - Exception when get request : cannot access local variable 'spark_s' where it is not associated with a value
[2024-11-08T09:30:29.496+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-08T09:30:29.529+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-08T09:30:29.530+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=api_test_v1, task_id=test_api, run_id=scheduled__2024-11-07T00:00:00+00:00, execution_date=20241107T000000, start_date=20241108T093027, end_date=20241108T093029
[2024-11-08T09:30:29.594+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-08T09:30:29.615+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-08T09:30:29.619+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
